version: '2.2' # specify docker-compose version
 
# Define the services/ containers to be run
services:
#  database: # name of the third service
#   image: mongo # specify image to build container from
#   restart: always
#   volumes:
#   - './data:/data/db'
#   ports:
#   - 27057:27017 # specify port forwarding

 backend: # name of the second service
  build: ./ # specify the directory of the Dockerfile
  ports:
  - 8000:80 #specify ports mapping
  volumes:
  - ./app:/code/app
